services:
  backend-dev:
    build:
      context: .
      dockerfile: server/Dockerfile.server
      target: dev
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://iamamanul:amanul9498@amancluster.xdcvafp.mongodb.net/chatapp_db?retryWrites=true&w=majority&appName=AmanCluster
    depends_on:
      - db

  frontend-dev:
    build:
      context: .
      dockerfile: client/Dockerfile.client
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules  # This prevents node_modules from being overwritten
    ports:
      - "5173:5173" # Map host port 3000 to container port 5173
    environment:
      - NODE_ENV=development
      # - REACT_APP_API_URL=http://localhost:5000   # Should point to backend port
      - VITE_BACKEND_URL=http://host.docker.internal:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend-dev

  backend-prod:
    build:
      context: .
      dockerfile: server/Dockerfile.server
      target: prod
    ports:
      - "8080:6000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://iamamanul:amanul9498@amancluster.xdcvafp.mongodb.net/chatapp_db?retryWrites=true&w=majority&appName=AmanCluster
    depends_on:
      - db

  frontend-prod:
    build:
      context: .
      dockerfile: client/Dockerfile.client
      target: prod
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend-prod

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mern_db:/data/db

volumes:
  mern_db: