name: Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # --- MongoDB Environment Variables ---
      # IMPORTANT: These should be set as secrets in your GitHub repository settings
      # Go to your repository > Settings > Secrets and variables > Actions > New repository secret
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      NODE_ENV: production

      # --- Cloudinary Keys ---
      # IMPORTANT: These should be set as secrets
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      # --- Frontend Environment Variables ---
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './client/package-lock.json'
    
    - name: "Installing Frontend Dependencies"
      run: |
        cd client
        npm i
    
    - name: "Build Frontend"
      run: |
        cd client
        npm run build
    
    - name: "Installing Backend Dependencies"
      run: |
        cd server
        npm i
    
    - name: "Validate Backend Syntax"
      run: |
        cd server
        node -c server.js
        echo "✅ Backend syntax validation passed"
    
    - name: "Check Backend Dependencies"
      run: |
        cd server
        npm audit --audit-level=moderate || echo "⚠️ Security audit completed with warnings"
    
    - name: "Test Backend"
      run: |
        cd server
        npm test || echo "No tests configured"
    
    - name: "Validate Backend Environment"
      run: |
        cd server
        echo "Checking if server.js exists..."
        ls -la server.js
        echo "Checking if package.json is valid..."
        node -e "console.log('✅ package.json is valid')"

    # --- Telegram Notification Step ---
    # This step is now correctly nested under the 'steps' of the 'build' job.
    - name: Telegram Notification
      # This makes sure the notification is sent even if previous steps fail
      if: always()
      run: |
        send_telegram_message() {
          local message="$1"
          curl -s -X POST \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="$message" \
          -d parse_mode="Markdown" \
          -d disable_web_page_preview=true
        }

        # Determine workflow status
        WORKFLOW_STATUS="Unknown"
        STATUS_EMOJI=""
        if [[ "${{ job.status }}" == "success" ]]; then
          WORKFLOW_STATUS="SUCCESS ✅"
          STATUS_EMOJI="✅"
        elif [[ "${{ job.status }}" == "failure" ]]; then
          WORKFLOW_STATUS="FAILED ❌"
          STATUS_EMOJI="❌"
        elif [[ "${{ job.status }}" == "cancelled" ]]; then
          WORKFLOW_STATUS="CANCELLED 🚫"
          STATUS_EMOJI="🚫"
        fi

        # Get the commit SHA
        COMMIT_SHA="${{ github.sha }}"
        # Get the short commit SHA
        SHORT_COMMIT_SHA="${{ github.sha_short }}"

        # Sanitize repository name for Markdown
        REPOSITORY_NAME="${{ github.repository }}"
        REPOSITORY_NAME_SANITIZED=$(echo "$REPOSITORY_NAME" | sed 's@_@\\_@g')

        # Construct the message
        MESSAGE="*QuickChat Integration Status Report* ${STATUS_EMOJI}

        *Repository:* $REPOSITORY_NAME_SANITIZED
        *Workflow:* ${{ github.workflow }}
        *Status:* *$WORKFLOW_STATUS*
        *Commit:* \`${SHORT_COMMIT_SHA}\`
        *Branch:* \`${{ github.ref_name }}\`

        *Check full details here:*
        [View Workflow Run](${{ github.server_url }}/$REPOSITORY_NAME/actions/runs/${{ github.run_id }})"

        send_telegram_message "$MESSAGE" 